### PR TITLE
Update sse.py

### PR DESCRIPTION
**Pull request by Hamsanger**
Add optional `event_id` parameter to `SSE.send()` method.

For use cases where the client resets the EventSource connection, so that the client state can be gracefully restored in sync with the server.  It should also make handling event streams from multiple clients easier.

The server request handler can check the "Last-Event-ID" value (if present) in the request header which should be set automatically when a client EventSource reconnects, and then set a starting point for resuming the data stream on that endpoint.  For example:

```py
@app.route("/status")
@with_sse
async def status_handler(request, sse):
    last_event_id = request.headers.get("Last-Event-ID", "")
    ...

```

### CODE REVIEW

**Comment by Hamsanger** [comment]
I didn't update the tests for this mod.  Did you want me to include test changes in the PR?

**Comment by miguelgrinberg** [comment]
Yes, please. I can't add this if it is not tested. Thanks.

**Comment by Hamsanger** [comment]
Ok, I have updated the test for sse.send() to include a couple of cases with the `event_id` parameter set.
PS: Thanks for putting together a great little web framework with such a comprehensive feature set.

**Comment by miguelgrinberg** [comment]
Thanks!

**Pull request merged**
